#ifndef APPLICATIONS_PIN_CONFIG_H_
#define APPLICATIONS_PIN_CONFIG_H_

//IO
#define GREEN_PIN 39
#define RED_PIN 98
#define BLUE_PIN 23

#define SCL_PIN 43
#define SDA_PIN 42

#endif /* APPLICATIONS_PIN_CONFIG_H_ */
